### ISSUE TITLE
pip install brotherprint fails - no README.md

### ISSUE THREAD

**Issue by adorsett** [fozzle/python-brotherprint#4]
Trying to install via pip fails with file not found for README.md.  Grabbed the tar.gz from https://pypi.python.org/pypi/brotherprint/0.1.2 and unpacked it by hand.  README.md is definitely missing from the archive.

Thanks!
Andrew

**Comment by misterhayman** [comment]
Also see the same issue.

Finished processing dependencies for pip
Collecting brotherprint
  Downloading brotherprint-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-MA_teO/brotherprint/setup.py", line 12, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by QuimeraCoding** [comment]
+ one..

**Comment by brenouchoa** [comment]
same problem... I used this before without any problems

**Comment by fozzle** [comment]
I've updated the package to include a README...not sure what happened there, sorry.

**Comment by misterhayman** [comment]
Thanks!  This package is awesome.
